/*
 * CANCommunicateProtocol.h
 *
 *  Created on: 2018年6月5日
 *      Author: xin-FFTAI
 */

#ifndef ROBOTSYSTEMFILES_HARDWAREINTERFACE_MOTOR_DRIVER_COMMUNICATE_PROTOCOL_CAN_COMMUNICATE_PROTOCOL_CAN_COMMUNICATE_PROTOCOL_H_
#define ROBOTSYSTEMFILES_HARDWAREINTERFACE_MOTOR_DRIVER_COMMUNICATE_PROTOCOL_CAN_COMMUNICATE_PROTOCOL_CAN_COMMUNICATE_PROTOCOL_H_

class CANCommunicateProtocol {

};



#endif /* ROBOTSYSTEMFILES_HARDWAREINTERFACE_MOTOR_DRIVER_COMMUNICATE_PROTOCOL_CAN_COMMUNICATE_PROTOCOL_CAN_COMMUNICATE_PROTOCOL_H_ */
