/*
 * serialPort_hardware_interface.h
 *
 *  Created on: 2018年6月1日
 *      Author: xin
 */

#ifndef ROBOTSYSTEMFILES_HARDWARELEVEL_SERIALPORT_INTERFACE_SERIALPORT_HARDWARE_INTERFACE_H_
#define ROBOTSYSTEMFILES_HARDWARELEVEL_SERIALPORT_INTERFACE_SERIALPORT_HARDWARE_INTERFACE_H_

class SerialPortHardwareInterface {

public:
	serialPort_init();
};

#endif /* ROBOTSYSTEMFILES_HARDWARELEVEL_SERIALPORT_INTERFACE_SERIALPORT_HARDWARE_INTERFACE_H_ */
