/*
 * ExInterrupt_hardware_interface.h
 *
 *  Created on: 2018年6月1日
 *      Author: xin
 */

#ifndef ROBOTSYSTEMFILES_HARDWARELEVEL_EXINTERRUPT_INTERFACE_EXINTERRUPT_HARDWARE_INTERFACE_H_
#define ROBOTSYSTEMFILES_HARDWARELEVEL_EXINTERRUPT_INTERFACE_EXINTERRUPT_HARDWARE_INTERFACE_H_

class ExInerruptHardwareInterface {

public:
	virtual int exInterrupt_init(void);

};

#endif /* ROBOTSYSTEMFILES_HARDWARELEVEL_EXINTERRUPT_INTERFACE_EXINTERRUPT_HARDWARE_INTERFACE_H_ */
